### ISSUE TITLE
Gravity Direction

### ISSUE THREAD

**Issue by zhoujun-7** [rongakowang/DeepSimHO#2]
Hi Wang,

Thanks for your sharing codes. The "hand_verts" and "obj_verts" are in camera coordinate, which are directly fed to MuJoCo for physical simulation. Is the gravity in MuJoCo aligned with real world? And what is the direction of MuJoCo gravity?

Looking forward to your reply.

Best,
Jun

**Comment by rongakowang** [comment]
Hi Jun:

We made the assumption that the world gravity roughly aligns with the camera coordinate (y axis in the image space) and MuJoCo environment is set to reflect this. You can visualize the xml model in MuJoCo for a better understanding.

**Comment by zhoujun-7** [comment]
Thanks for your answer.
